CREATE TABLE countries
(
    id serial NOT NULL
        CONSTRAINT countries_pkey
        PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    isd_code        VARCHAR(10),
    code_iso_alpha_2 VARCHAR(2) NOT NULL,
    date_created      TIMESTAMP WITH TIME ZONE DEFAULT now(),
    date_modified     TIMESTAMP WITH TIME ZONE DEFAULT now(),
    status            VARCHAR(20) NOT NULL
);
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Afghanistan','ACTIVE','93','AF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Åland Islands','ACTIVE','35818','AX');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Albania','ACTIVE','355','AL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Algeria','ACTIVE','213','DZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('American Samoa','ACTIVE','1684','AS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Andorra','ACTIVE','376','AD');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Angola','ACTIVE','244','AO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Anguilla','ACTIVE','1264','AI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Antarctica','ACTIVE','','AQ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Antigua and Barbuda','ACTIVE','1268','AG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Argentina','ACTIVE','54','AR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Armenia','ACTIVE','374','AM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Aruba','ACTIVE','297','AW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Australia','ACTIVE','61','AU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Austria','ACTIVE','43','AT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Azerbaijan','ACTIVE','994','AZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bahamas','ACTIVE','1242','BS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bahrain','ACTIVE','973','BH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bangladesh','ACTIVE','880','BD');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Barbados','ACTIVE','1246','BB');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Belarus','ACTIVE','375','BY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Belgium','ACTIVE','32','BE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Belize','ACTIVE','501','BZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Benin','ACTIVE','229','BJ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bermuda','ACTIVE','1441','BM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bhutan','ACTIVE','975','BT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bolivia, Plurinational State of','ACTIVE','591','BO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bonaire, Sint Eustatius and Saba','ACTIVE','5997','BQ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bosnia and Herzegovina','ACTIVE','387','BA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Botswana','ACTIVE','267','BW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bouvet Island','ACTIVE','','BV');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Brazil','ACTIVE','55','BR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('British Indian Ocean Territory','ACTIVE','246','IO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Brunei Darussalam','ACTIVE','673','BN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Bulgaria','ACTIVE','359','BG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Burkina Faso','ACTIVE','226','BF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Burundi','ACTIVE','257','BI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cambodia','ACTIVE','855','KH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cameroon','ACTIVE','237','CM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Canada','ACTIVE','1','CA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cape Verde','ACTIVE','238','CV');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cayman Islands','ACTIVE','1345','KY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Central African Republic','ACTIVE','236','CF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Chad','ACTIVE','235','TD');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Chile','ACTIVE','56','CL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('China','ACTIVE','86','CN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Christmas Island','ACTIVE','6189164','CX');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cocos (Keeling) Islands','ACTIVE','6189162','CC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Colombia','ACTIVE','57','CO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Comoros','ACTIVE','269','KM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Congo','ACTIVE','242','CG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Congo, the Democratic Republic of the','ACTIVE','243','CD');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cook Islands','ACTIVE','682','CK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Costa Rica','ACTIVE','506','CR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Côte d''Ivoire','ACTIVE','','CI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Croatia','ACTIVE','','HR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cuba','ACTIVE','53','CU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Curaçao','ACTIVE','5999','CW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Cyprus','ACTIVE','357','CY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Czech Republic','ACTIVE','420','CZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Denmark','ACTIVE','45','DK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Djibouti','ACTIVE','253','DJ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Dominica','ACTIVE','1767','DM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Dominican Republic','ACTIVE','','DO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Ecuador','ACTIVE','593','EC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Egypt','ACTIVE','20','EG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('El Salvador','ACTIVE','503','SV');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Equatorial Guinea','ACTIVE','240','GQ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Eritrea','ACTIVE','291','ER');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Estonia','ACTIVE','372','EE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Ethiopia','ACTIVE','251','ET');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Falkland Islands (Malvinas)','ACTIVE','500','FK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Faroe Islands','ACTIVE','298','FO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Fiji','ACTIVE','679','FJ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Finland','ACTIVE','358','FI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('France','ACTIVE','33','FR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('French Guiana','ACTIVE','594','GF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('French Polynesia','ACTIVE','689','PF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('French Southern Territories','ACTIVE','','TF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Gabon','ACTIVE','241','GA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Gambia','ACTIVE','220','GM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Georgia','ACTIVE','995','GE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Germany','ACTIVE','49','DE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Ghana','ACTIVE','233','GH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Gibraltar','ACTIVE','350','GI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Greece','ACTIVE','30','GR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Greenland','ACTIVE','299','GL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Grenada','ACTIVE','1473','GD');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Guadeloupe','ACTIVE','590','GP');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Guam','ACTIVE','1671','GU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Guatemala','ACTIVE','502','GT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Guernsey','ACTIVE','','GG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Guinea','ACTIVE','224','GN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Guinea-Bissau','ACTIVE','245','GW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Guyana','ACTIVE','592','GY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Haiti','ACTIVE','509','HT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Heard Island and McDonald Islands','ACTIVE','','HM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Holy See (Vatican City State)','ACTIVE','','VA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Honduras','ACTIVE','504','HN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Hong Kong','ACTIVE','852','HK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Hungary','ACTIVE','36','HU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Iceland','ACTIVE','354','IS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('India','ACTIVE','91','IN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Indonesia','ACTIVE','62','ID');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Iran, Islamic Republic of','ACTIVE','98','IR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Iraq','ACTIVE','964','IQ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Ireland','ACTIVE','353','IE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Isle of Man','ACTIVE','','IM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Israel','ACTIVE','972','IL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Italy','ACTIVE','39','IT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Jamaica','ACTIVE','1876','JM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Japan','ACTIVE','81','JP');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Jersey','ACTIVE','441534','JE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Jordan','ACTIVE','962','JO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Kazakhstan','ACTIVE','','KZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Kenya','ACTIVE','254','KE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Kiribati','ACTIVE','686','KI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Korea, Democratic People''s Republic of','ACTIVE','','KP');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Korea, Republic of','ACTIVE','850','KR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Kuwait','ACTIVE','965','KW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Kyrgyzstan','ACTIVE','996','KG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Lao People''s Democratic Republic','ACTIVE','','LA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Latvia','ACTIVE','371','LV');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Lebanon','ACTIVE','961','LB');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Lesotho','ACTIVE','266','LS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Liberia','ACTIVE','231','LR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Libya','ACTIVE','218','LY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Liechtenstein','ACTIVE','423','LI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Lithuania','ACTIVE','370','LT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Luxembourg','ACTIVE','352','LU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Macao','ACTIVE','','MO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Macedonia, the Former Yugoslav Republic of','ACTIVE','389','MK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Madagascar','ACTIVE','261','MG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Malawi','ACTIVE','265','MW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Malaysia','ACTIVE','60','MY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Maldives','ACTIVE','960','MV');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Mali','ACTIVE','223','ML');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Malta','ACTIVE','356','MT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Marshall Islands','ACTIVE','692','MH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Martinique','ACTIVE','596','MQ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Mauritania','ACTIVE','222','MR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Mauritius','ACTIVE','230','MU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Mayotte','ACTIVE','','YT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Mexico','ACTIVE','52','MX');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Micronesia, Federated States of','ACTIVE','691','FM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Moldova, Republic of','ACTIVE','373','MD');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Monaco','ACTIVE','377','MC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Mongolia','ACTIVE','976','MN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Montenegro','ACTIVE','382','ME');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Montserrat','ACTIVE','1664','MS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Morocco','ACTIVE','212','MA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Mozambique','ACTIVE','258','MZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Myanmar','ACTIVE','95','MM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Namibia','ACTIVE','264','NA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Nauru','ACTIVE','674','NR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Nepal','ACTIVE','977','NP');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Netherlands','ACTIVE','31','NL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('New Caledonia','ACTIVE','687','NC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('New Zealand','ACTIVE','64','NZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Nicaragua','ACTIVE','505','NI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Niger','ACTIVE','227','NE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Nigeria','ACTIVE','234','NG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Niue','ACTIVE','683','NU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Norfolk Island','ACTIVE','6723','NF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Northern Mariana Islands','ACTIVE','1670','MP');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Norway','ACTIVE','47','NO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Oman','ACTIVE','968','OM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Pakistan','ACTIVE','92','PK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Palau','ACTIVE','680','PW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Palestine, State of','ACTIVE','970','PS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Panama','ACTIVE','507','PA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Papua New Guinea','ACTIVE','675','PG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Paraguay','ACTIVE','595','PY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Peru','ACTIVE','51','PE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Philippines','ACTIVE','63','PH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Pitcairn','ACTIVE','','PN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Poland','ACTIVE','48','PL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Portugal','ACTIVE','351','PT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Puerto Rico','ACTIVE','','PR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Qatar','ACTIVE','974','QA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Réunion','ACTIVE','262','RE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Romania','ACTIVE','40','RO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Russian Federation','ACTIVE','7','RU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Rwanda','ACTIVE','250','RW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saint Barthélemy','ACTIVE','590','BL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saint Helena, Ascension and Tristan da Cunha','ACTIVE','290','SH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saint Kitts and Nevis','ACTIVE','1869','KN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saint Lucia','ACTIVE','1758','LC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saint Martin (French part)','ACTIVE','590','MF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saint Pierre and Miquelon','ACTIVE','508','PM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saint Vincent and the Grenadines','ACTIVE','1784','VC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Samoa','ACTIVE','685','WS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('San Marino','ACTIVE','378','SM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Sao Tome and Principe','ACTIVE','','ST');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Saudi Arabia','ACTIVE','966','SA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Senegal','ACTIVE','221','SN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Serbia','ACTIVE','381','RS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Seychelles','ACTIVE','248','SC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Sierra Leone','ACTIVE','232','SL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Singapore','ACTIVE','65','SG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Sint Maarten (Dutch part)','ACTIVE','5993','SX');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Slovakia','ACTIVE','421','SK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Slovenia','ACTIVE','386','SI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Solomon Islands','ACTIVE','677','SB');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Somalia','ACTIVE','252','SO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('South Africa','ACTIVE','27','ZA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('South Georgia and the South Sandwich Islands','ACTIVE','500','GS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('South Sudan','ACTIVE','211','SS');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Spain','ACTIVE','34','ES');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Sri Lanka','ACTIVE','94','LK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Sudan','ACTIVE','249','SD');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Suriname','ACTIVE','597','SR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Svalbard and Jan Mayen','ACTIVE','4779','SJ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Swaziland','ACTIVE','268','SZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Sweden','ACTIVE','46','SE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Switzerland','ACTIVE','41','CH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Syrian Arab Republic','ACTIVE','963','SY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Taiwan, Province of China','ACTIVE','886','TW');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Tajikistan','ACTIVE','992','TJ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Tanzania, United Republic of','ACTIVE','255','TZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Thailand','ACTIVE','66','TH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Timor-Leste','ACTIVE','88216','TL');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Togo','ACTIVE','228','TG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Tokelau','ACTIVE','690','TK');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Tonga','ACTIVE','676','TO');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Trinidad and Tobago','ACTIVE','1868','TT');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Tunisia','ACTIVE','216','TN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Turkey','ACTIVE','90','TR');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Turkmenistan','ACTIVE','993','TM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Turks and Caicos Islands','ACTIVE','1649','TC');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Tuvalu','ACTIVE','688','TV');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Uganda','ACTIVE','256','UG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Ukraine','ACTIVE','380','UA');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('United Arab Emirates','ACTIVE','971','AE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('United Kingdom','ACTIVE','44','GB');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('United States','ACTIVE','1','US');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('United States Minor Outlying Islands','ACTIVE','','UM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Uruguay','ACTIVE','598','UY');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Uzbekistan','ACTIVE','998','UZ');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Vanuatu','ACTIVE','678','VU');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Venezuela, Bolivarian Republic of','ACTIVE','','VE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Viet Nam','ACTIVE','','VN');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Virgin Islands, British','ACTIVE','84','VG');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Virgin Islands, U.S.','ACTIVE','','VI');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Wallis and Futuna','ACTIVE','681','WF');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Western Sahara','ACTIVE','','EH');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Yemen','ACTIVE','967','YE');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Zambia','ACTIVE','260','ZM');
INSERT INTO countries (name, status, isd_code, code_iso_alpha_2) values('Zimbabwe','ACTIVE','263','ZW');